---
- name: Install postgres
  apt: name=postgresql-9.4 state=present
  register: __postgres9_installed

# - name: Initializes database
#   command: service postgresql initdb
#   when: __postgres9_installed.changed

- name: Ensure postgres is started
  service: name=postgresql state=started enabled=yes

- name: Installs useful packages
  apt: name={{item}} state=present
  with_items:
    - python-psycopg2
    - libpq-dev
    - sudo
  notify: Restart postgres

- name: Configures postgres
  template: src={{ item }}.j2 dest=/etc/postgresql/9.4/main/{{ item }}
  with_items:
    - pg_hba.conf # need to
    - postgresql.conf # need to write good conf
  notify: Restart postgres

# force hanfler (strange bug)
- meta: flush_handlers

- name: Create User {{postgres9_user_name}}
  sudo: yes
  sudo_user: postgres
  postgresql_user: >
    user="{{postgres9_user_name}}"
    password="{{postgres9__user_password}}"
    role_attr_flags=CREATEDB,NOSUPERUSER

- name: Create Database {{postgres9_db_name}}
  sudo: yes
  sudo_user: postgres
  postgresql_db: >
    name=""{{postgres9_db_name}}""
    owner="{{postgres9_user_name}}"
    login_user="{{postgres9_user_name}}"
    login_password="{{postgres9__user_password}}"
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'