---
- name: Install postgres
  apt: name=postgresql-9.4 state=present
  register: __postgres9_installed

# - name: Initializes database
#   command: service postgresql initdb
#   when: __postgres9_installed.changed

- name: Ensure postgres is started
  service: name=postgresql state=started enabled=yes

- name: Installs useful packages
  apt: name={{item}} state=present
  with_items:
    - python-psycopg2
    - libpq-dev
    - sudo
  notify: Restart postgres

- name: Configures postgres
  template: src={{ item }}.j2 dest=/etc/postgresql/9.4/main/{{ item }}
  with_items:
    - pg_hba.conf # need to
    - postgresql.conf # need to write good conf
  notify: Restart postgres

# force hanfler (strange bug)
- meta: flush_handlers

# TODO : variabilize
- name: Create User insacloud
  sudo: yes
  sudo_user: postgres
  postgresql_user: >
    user=insacloud
    password=insacloud
    role_attr_flags=CREATEDB,NOSUPERUSER

# TODO : variabilize
- name: Create Database insacloud
  sudo: yes
  sudo_user: postgres
  postgresql_db: >
    name=insacloud
    owner=insacloud
    login_user=insacloud
    login_password=insacloud
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'

# REPLACE TODO
#- postgresql_user: db=insacloud name=insacloud password=insacloud priv=CONNECT/far:ALL