import ImageFormatter
from PIL import Image
import math
import random

# Algo var
imageDim = 512 # all images will have imageDim*imageDim pixels
mosaicDim = 64 # mosaic will have mosaicDim*mosaicDim images
nbTilesPerDim = 4 # mosaic will have nbTilesPerDim*nbTilesPerDim tiles
tileDim = int(mosaicDim/nbTilesPerDim) # tile will have tileDim*tileDim images
mosaic = Image.new('L', (imageDim*nbTilesPerDim, imageDim*nbTilesPerDim)) # mosaic is generated by merging tiles

# create mosaicDim*mosaicDim matrix
mosaicMatrix = [[0 for i in range(mosaicDim)] for i in range(mosaicDim)]

# Open Image :
imFormat =ImageFormatter.ImageFormatter("troll512x512.png")
# ?
color = imFormat.process_image(imageDim)
# ?
image = imFormat.get_image()
# ?
pixel = image.load()

# TODO - Build this dictionnary
hueMap = {"1":[image]}

def find_closest_available_hue(targetHue, hueMap):
    if(str(targetHue) in hueMap):
        return hueMap[str(targetHue)][random.randint(0,len(hueMap[str(targetHue)])-1)]
    min=256
    k = None
    for key in hueMap:
        hue = int(key)
        if(abs(hue - targetHue) < min):
            min = abs(hue - targetHue)
            k = key
    return hueMap[k][random.randint(0,len(hueMap[k])-1)]

# feed mosaicMatrix with mosaicDim*mosaicDim images
for x in range(mosaicDim):
    for y in range(mosaicDim):
        hue = pixel[x,y]
        find_closest_available_hue(hue, hueMap)
        mosaicMatrix[x][y] = image

# generate tiles and mosaic
# might be functionalized (huge nb of vars+)
for i in range(0, nbTilesPerDim, 1): # 
    for j in range(0, nbTilesPerDim, 1):
        tile = Image.new('L', (imageDim*tileDim,imageDim*tileDim))
        for k in range(i*tileDim, (i+1)*tileDim, 1):
            for l in range(j*tileDim, (j+1)*tileDim, 1):
                # build tile with merging images
                tile.paste(mosaicMatrix[k][l], ((k%tileDim)*imageDim, (l%tileDim)*imageDim,((k%tileDim)+1)*imageDim, ((l%tileDim)+1)*imageDim))
        # resize tile image
        tile = tile.resize((imageDim,imageDim), Image.ANTIALIAS)
        # build mosaic with merging tiles
        mosaic.paste(tile, ((i%nbTilesPerDim)*imageDim, (j%nbTilesPerDim)*imageDim,((i%nbTilesPerDim)+1)*imageDim, ((j%nbTilesPerDim)+1)*imageDim))
        # export mosaic image
        tile.save("tile-"+str(i)+"-"+str(j)+".jpg", "JPEG")

# resize mosaic image
mosaic = mosaic.resize((imageDim,imageDim), Image.ANTIALIAS)
# export mosaic image
mosaic.save("mosaic.jpg", "JPEG")