---
###############################################################################
# Install packages ############################################################
###############################################################################
- name: Install required packages
  apt: name={{item}} state=installed
  with_items:
   - postgresql-client-9.4
   - libpq-dev
   - git
   - libjpeg-dev # pillow (django image model)
   - supervisor=3.0r1-1

- name: Symbolic sources link
  file: src={{insacloud_path_repo}}/{{insacloud_appname}} dest={{insacloud_virtualenv_path}}/{{insacloud_appname}} owner={{insacloud_user.name}} group={{insacloud_user.group}} state=link

# test && remove
# - name: Set sources folder permissions
#   file: path={{insacloud_path_repo}}/{{insacloud_appname}} recurse=yes state=directory owner={{insacloud_user.name}} group={{insacloud_user.group}}

###############################################################################
# Init Django #################################################################
###############################################################################

- name: Install project requirements
  pip: requirements={{insacloud_virtualenv_path}}/{{insacloud_appname}}/requirements.txt virtualenv={{insacloud_virtualenv_path}}

# replace dest if we need to run vagrant with admin rights
- name: Generate django conf
  template: src=local_settings.py.j2 dest=/tmp/local_settings.py  owner={{insacloud_user.name}} group={{insacloud_user.group}} # dest={{insacloud_path_repo}}/{{insacloud_appname}}/{{insacloud_appname}}/local_settings.py

# remove if we need to run vagrant with admin rights
- name: Copy django conf - windows/vagrant workaround
  command: cp -f /tmp/local_settings.py {{insacloud_path_repo}}/{{insacloud_appname}}/{{insacloud_appname}}/local_settings.py
  changed_when: False

- name: Create upload folder
  file: path={{insacloud_django_upload_path}} recurse=yes state=directory owner={{insacloud_user.name}} group={{insacloud_user.group}}

- name: Run the Django syncdb command
  django_manage:
    command: makemigrations
    app_path: "{{insacloud_virtualenv_path}}/{{insacloud_appname}}"
    virtualenv: "{{ insacloud_virtualenv_path }}"
    settings: "insacloud.local_settings"

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{insacloud_virtualenv_path}}/{{insacloud_appname}}"
    virtualenv: "{{ insacloud_virtualenv_path }}"
    settings: "insacloud.local_settings"

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{insacloud_virtualenv_path}}/{{insacloud_appname}}"
    virtualenv: "{{ insacloud_virtualenv_path }}"
    settings: "insacloud.local_settings"

###############################################################################
# Configuration files #########################################################
###############################################################################

- name: Generate gunicorn launcher
  template: src=gunicorn_start.j2 dest={{insacloud_virtualenv_path}}/bin/gunicorn_start owner={{insacloud_user.name}} group={{insacloud_user.group}} mode=0755

- name: Removes nginx default servers
  file: path=/etc/nginx/sites-enabled/{{item}} state=absent
  with_items:
    - default

- name: Set insacloud nginx conf
  template: src=nginx-insacloud.j2 dest=/etc/nginx/sites-enabled/insacloud
  notify: Restart nginx

# force hanfler (strange bug)
- meta: flush_handlers

## TODO prod
## - name: Set insacloud nginx conf
##   template: src=.htpassword.insacloud.com.j2 dest=/etc/nginx/passwords/.htpassword.insacloud.com
##   notify: Restart nginx

# dirty : to remove when data feed will be implemented
- name: Create initial django superuser - script
  template: src=create_initial_superuser.sh.j2 dest=/tmp/create_initial_superuser.sh owner={{insacloud_user.name}} group={{insacloud_user.group}}

# dirty : to remove when data feed will be implemented
- name: Run initial django superuser script
  script: /tmp/create_initial_superuser.sh
  changed_when: False

- name: Set insacloud supervisor conf
  template: src=supervisor-insacloud.conf.j2 dest=/etc/supervisor/conf.d/insacloud.conf
  notify: Restart nginx

# force hanfler (strange bug)
- meta: flush_handlers

###############################################################################
# [re]Start services ##########################################################
###############################################################################

- name: set permissions
  file: path={{insacloud_virtualenv_path}} recurse=yes state=directory owner={{insacloud_user.name}} group={{insacloud_user.group}}

- name: Re-read the Supervisor config files
  supervisorctl: name={{ insacloud_appname }} state=present

- name: Restart Supervisor
  supervisorctl: name={{ insacloud_appname }} state=restarted