---
- name: Install required packages
  apt: name={{item}} state=installed
  with_items:
   - postgresql-client-9.4
   - libpq-dev
   - git

- name: Create virtual env folder
  file: path={{ insacloud_virtualenv_path }} state=directory mode=0755

# only works from ansible 2.0
#- name: Create virtual env and install requirements
#  pip: requirements=/{{insacloud_virtualenv_path}}/{{insacloud_appname}}/requirements.txt virtualenv={{insacloud_virtualenv_path}} virtualenv_python=python3.4 virtualenv_site_packages=no

# check if virtualenv already exists
- stat: path={{insacloud_virtualenv_path}}/bin/activate
  register: virtualenv

- name: Install virtualenv
  shell: virtualenv -p /usr/local/bin/python3.4 --no-site-packages {{insacloud_virtualenv_path}}
  changed_when: virtualenv.stat.exists == False
  when: virtualenv.stat.exists == False

# - name: Install env requirements
#   pip: name={{item}} virtualenv={{insacloud_virtualenv_path}}
#   with_items:
#    - psycopg2
#    - gunicorn
#    - django
#    - setproctitle # show gunicorn name process (eg. ps command)

# replace
- name: Symbolic sources link
  file: src={{insacloud_path_repo}}/{{insacloud_appname}} dest={{insacloud_virtualenv_path}}/{{insacloud_appname}} owner={{insacloud_user.name}} group={{insacloud_user.group}} state=link

- name: Set sources folder permissions
  file: path={{insacloud_path_repo}}/{{insacloud_appname}} recurse=yes state=directory owner={{insacloud_user.name}} group={{insacloud_user.group}}

- name: Install project requirements
  pip: requirements={{insacloud_virtualenv_path}}/{{insacloud_appname}}/requirements.txt virtualenv={{insacloud_virtualenv_path}}

- name: Generate django conf
  template: src=local_settings.py.j2 dest=/tmp/local_settings.py  owner={{insacloud_user.name}} group={{insacloud_user.group}} # dest={{insacloud_path_repo}}/{{insacloud_appname}}/{{insacloud_appname}}/local_settings.py

# remove if we need to run vagrant with admin rights
- name: Copy django conf - windows/vagrant workaround
  command: cp -f /tmp/local_settings.py {{insacloud_path_repo}}/{{insacloud_appname}}/{{insacloud_appname}}/local_settings.py
  changed_when: False

- name: Run the Django syncdb command
  django_manage:
    command: makemigrations
    app_path: "{{insacloud_virtualenv_path}}/{{insacloud_appname}}"
    virtualenv: "{{ insacloud_virtualenv_path }}"
    settings: "insacloud.local_settings"

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{insacloud_virtualenv_path}}/{{insacloud_appname}}"
    virtualenv: "{{ insacloud_virtualenv_path }}"
    settings: "insacloud.local_settings"

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{insacloud_virtualenv_path}}/{{insacloud_appname}}"
    virtualenv: "{{ insacloud_virtualenv_path }}"
    settings: "insacloud.local_settings"

- name: Generate gunicorn launcher
  template: src=gunicorn_start.j2 dest={{insacloud_virtualenv_path}}/bin/gunicorn_start owner={{insacloud_user.name}} group={{insacloud_user.group}} mode=0755

- name: Ensure supervisor is installed
  apt: name=supervisor=3.0r1-1 state=present

- name: Removes nginx default servers
  file: path=/etc/nginx/sites-enabled/{{item}} state=absent
  with_items:
    - default

- name: Set insacloud nginx conf
  template: src=nginx-insacloud.j2 dest=/etc/nginx/sites-enabled/insacloud
  notify: Restart nginx

# force hanfler (strange bug)
- meta: flush_handlers

## TODO prod
## - name: Set insacloud nginx conf
##   template: src=.htpassword.insacloud.com.j2 dest=/etc/nginx/passwords/.htpassword.insacloud.com
##   notify: Restart nginx

# dirty : to remove when data feed will be implemented
- name: Create initial django superuser - script
  template: src=create_initial_superuser.sh.j2 dest=/tmp/create_initial_superuser.sh owner={{insacloud_user.name}} group={{insacloud_user.group}}

# dirty : to remove when data feed will be implemented
- name: Run initial django superuser script
  script: /tmp/create_initial_superuser.sh
  changed_when: False

- name: Set insacloud supervisor conf
  template: src=supervisor-insacloud.conf.j2 dest=/etc/supervisor/conf.d/insacloud.conf
  notify: Restart nginx

# force hanfler (strange bug)
- meta: flush_handlers

- name: Re-read the Supervisor config files
  supervisorctl: name={{ insacloud_appname }} state=present

- name: Restart Supervisor
  supervisorctl: name={{ insacloud_appname }} state=restarted